/*
Navicat MySQL Data Transfer

Source Server         : localhost_3306
Source Server Version : 50155
Source Host           : localhost:3306
Source Database       : drive

Target Server Type    : MYSQL
Target Server Version : 50155
File Encoding         : 65001

Date: 2019-07-09 17:19:24
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `t_question`
-- ----------------------------
DROP TABLE IF EXISTS `t_question`;
CREATE TABLE `t_question` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `types` varchar(20) NOT NULL,
  `subjectId` int(10) unsigned NOT NULL,
  `content` varchar(500) NOT NULL,
  `options` varchar(500) NOT NULL,
  `answers` varchar(60) NOT NULL,
  `totalNum` int(10) DEFAULT '0',
  `correctNum` int(10) DEFAULT '0',
  `resolve` varchar(500) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `question_subject` (`subjectId`),
  CONSTRAINT `question_subject` FOREIGN KEY (`subjectId`) REFERENCES `t_subject` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=88 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of t_question
-- ----------------------------
INSERT INTO `t_question` VALUES ('3', '1#5', '1', '<p><strong><span style=\"font-size:14px;font-family:宋体\">机动车驾驶人、行人违反道路交通安全法律、法规关于道路通行规定的行为，属于</span></strong></p>', '违章行为#违法行为#过失行为#过错行为#', '2#', '0', '0', '按这题的意思，“机动车驾驶人、行人违反道路交通安全法律、法规关于道路通行规定的行为”，题目说了，违反法律法规，不属于违章行为，也不属于过失行为，更不是过错行为。\n');
INSERT INTO `t_question` VALUES ('4', '1#5', '1', '<p><strong><span style=\"font-size: 10.5pt; font-family: 宋体;\">尚未登记的机动车，需要临时上道路行驶，应当</span></strong></p>', '取得临时通行牌证#到公安机关备案#直接上路行驶#在车窗上张贴合格证#', '1#', '0', '0', '《中华人民共和国道路交通安全法》第八条明确规定国家对机动车实行登记制度。机动车经公安机关交通管理部门登记后，方可上道路行驶。尚未登记的机动车，需要临时上道路行驶的，应当取得临时通行牌证，因此答案为A。\n');
INSERT INTO `t_question` VALUES ('5', '1#5', '1', '<p><strong><span style=\"font-size: 14px;font-family: 宋体\">已达到报废标准的机动车</span><span style=\"text-decoration:underline;\"><span style=\"font-size: 14px;font-family: 宋体\">&nbsp;&nbsp; </span></span><span style=\"font-size: 14px;font-family: 宋体\">上道路行驶。</span></strong></p>', '允许临时#不得#经维修后可以#缴管理费后可以#', '2#', '0', '0', '《中华人民共和国道路交通安全法》第十四条明确规定：达到报废标准的机动车不得上道路行驶。报废的大型客、货车及其他营运车辆应当在公安机关交通管理部门的监督下解体，因此答案为B。\n');
INSERT INTO `t_question` VALUES ('6', '1#5', '1', '<p><strong><span style=\"font-size:14px;font-family:宋体\">允许收缴、扣留机动车驾驶证的部门只有</span><span style=\"text-decoration:underline;\"><span style=\"font-size:14px;font-family:宋体\">&nbsp;&nbsp; </span></span><span style=\"font-size:14px;font-family:宋体\">。</span></strong></p>', '运输管理部门#公安机关交通管理部门#工商部门#税务部门#', '2#', '0', '0', '《中华人民共和国道路交通安全法》第十九条明确规定 公安机关交通管理部门以外的任何单位或者个人，不得收缴、扣留机动车驾驶证，因此答案为B 。\n');
INSERT INTO `t_question` VALUES ('7', '1#5', '1', '<p><strong><span style=\"font-size: 14px;font-family: 宋体\">驾驶人在道路上驾驶机动车时，</span><span style=\"text-decoration:underline;\"><span style=\"font-size: 14px;font-family: 宋体\">&nbsp;&nbsp; </span></span><span style=\"font-size: 14px;font-family: 宋体\">。</span></strong></p>', '只需携带驾驶证#只需携带行驶证#必须携带驾驶证、行驶证，放置强制保险标志、检验合格标志#应携带出厂合格证明或进口凭证#', '3#', '0', '0', '《中华人民共和国道路交通安全法》第十一条 驾驶机动车上道路行驶，应当悬挂机动车号牌，放置检验合格标志、保险标志，并随车携带机动车行驶证。 　　机动车号牌应当按照规定悬挂并保持清晰、完整，不得故意遮挡、污损。 　　任何单位和个人不得收缴、扣留机动车号牌。因此答案为C。');
INSERT INTO `t_question` VALUES ('8', '1#5', '1', '<p><strong><span style=\"font-size: 14px;font-family: 宋体\">驾驶机动车，必须遵守</span><span style=\"text-decoration:underline;\"><span style=\"font-size: 14px;font-family: 宋体\">&nbsp;&nbsp; </span></span><span style=\"font-size: 14px;font-family: 宋体\">的原则。</span></strong></p>', '右侧通行#左侧通行#内侧通行#中间通行#', '1#', '0', '0', '《中华人民共和国道路交通安全法》第三十五条明确规定 机动车、非机动车实行右侧通行,因此答案为A。');
INSERT INTO `t_question` VALUES ('9', '1#5', '1', '<p><strong><span style=\"font-size:14px;font-family:宋体\">没有划分机动车道、非机动车道和人行道的道路，机动车</span><span style=\"text-decoration:underline;\"><span style=\"font-size:14px;font-family:宋体\">&nbsp;&nbsp; </span></span><span style=\"font-size:14px;font-family:宋体\">。</span></strong></p>', '在道路两边通行#在道路中间通行#实行分道通行#可随意通行#', '2#', '0', '0', '《中华人民共和国道路交通安全法》第三十六条明确规定 　没有划分机动车道、非机动车道和人行道的，机动车在道路中间通行，非机动车和行人在道路两侧通行,因此答案为B。');
INSERT INTO `t_question` VALUES ('10', '1#5', '1', '<p><strong><span style=\"font-size: 14px;font-family: 宋体\">机动车遇交通警察现场指挥和交通信号不一致时，应当按照</span><span style=\"text-decoration:underline;\"><span style=\"font-size: 14px;font-family: 宋体\">&nbsp;&nbsp; </span></span><span style=\"font-size: 14px;font-family: 宋体\">通行。</span></strong></p>', '道路标志#交通信号灯的指挥#交通警察的指挥#道路标线#', '3#', '0', '0', '根据《中华人民共和国道路交通安全法》第四章第一节 第三十八条规定：车辆、行人应当按照交通信号通行；遇有交通警察现场指挥时，应当按照交通警察的指挥通行；在没有交通信号的道路上，应当在确保安全、畅通的原则下通行。 因此正确答案C\n');
INSERT INTO `t_question` VALUES ('11', '1#4', '1', '<p><strong><span style=\"font-size:14px;font-family:宋体\">机动车在设有最高限速标志的道路上行驶时，____。</span></strong></p>', '不得超过标明的最高时速#允许超过标明最高时速的10%#可以超过车辆的最高设计时速#必须按规定的最高车速行驶#', '1#', '0', '0', '看清题目，是“设有”，不是“没有”《中华人民共和国道路交通安全法》第四十二条明确规定 机动车上道路行驶，不得超过限速标志标明的最高时速。在没有限速标志的路段，应当保持安全车速,因此答案为A\n');
INSERT INTO `t_question` VALUES ('12', '1#5', '1', '<p><strong><span style=\"font-size: 14px;font-family: 宋体\">机动车通过没有交通信号灯、交通标志、交通标线或者交通警察指挥的交叉路口时，应当</span><span style=\"text-decoration:underline;\"><span style=\"font-size: 14px;font-family: 宋体\">&nbsp;&nbsp; </span></span><span style=\"font-size: 14px;font-family: 宋体\">。</span></strong></p>', '迅速通过#减速慢行#适当加速#保持行驶速度#', '2#', '0', '0', '《中华人民共和国道路交通安全法》第四十四条明确规定 　 机动车通过交叉路口，应当按照交通信号灯、交通标志、交通标线或者交通警察的指挥通过；通过没有交通信号灯、交通标志、交通标线或者交通警察指挥的交叉路口时，应当减速慢行，并让行人和优先通行的车辆先行,因此答案为B。');
INSERT INTO `t_question` VALUES ('13', '1#5', '1', '<p><strong><span style=\"font-size: 14px;font-family: 宋体\">在车道减少的路段、路口，机动车应当</span><span style=\"text-decoration:underline;\"><span style=\"font-size: 14px;font-family: 宋体\">&nbsp;&nbsp; </span></span><span style=\"font-size: 14px;font-family: 宋体\">。</span></strong></p>', '借道超车#依次交替通行#加速通过#抢道行驶#', '2#', '0', '0', '《中华人民共和国道路交通安全法》第四十五条明确规定 　　在车道减少的路段、路口，或者在没有交通信号灯、交通标志、交通标线或者交通警察指挥的交叉路口遇到停车排队等候或者缓慢行驶时，机动车应当依次交替通行,因此答案为B 。\n');
INSERT INTO `t_question` VALUES ('14', '1#5', '1', '<p><strong><span style=\"font-size:14px;font-family:宋体\">机动车通过没有交通信号或没有管理人员的铁道路口时，应</span><span style=\"text-decoration:underline;\"><span style=\"font-size:14px;font-family:宋体\">&nbsp;&nbsp; </span></span><span style=\"font-size:14px;font-family:宋体\">。</span></strong></p>', '按原来车速行驶#减速或停车观察#加速尽快通过#紧随前车行驶#', '2#', '0', '0', '《中华人民共和国道路交通安全法》第四十六条明确规定 机动车通过铁路道口时，应当按照交通信号或者管理人员的指挥通行；没有交通信号或者管理人员的，应当减速或者停车，在确认安全后通过，因此正确答案为B。');
INSERT INTO `t_question` VALUES ('15', '2#5', '1', '<p><strong><span style=\"font-size: 10.5pt; font-family: 宋体;\">在中华人民共和国境内与道路交通活动有关的单位和个人，都必须遵守《中华人民共和国道路交通安全法》。</span></strong></p>', '正确#错误#', '1#', '0', '0', '《中华人民共和国道路交通安全法实施条例》第一章 第二条 中华人民共和国境内的车辆驾驶人、行人、乘车人以及与道路交通活动有关的单位和个人，应当遵守道路交通安全法和本条例。因此答案为正确。');
INSERT INTO `t_question` VALUES ('16', '2#5', '1', '<p><strong><span style=\"font-size: 10.5pt; font-family: 宋体;\">机动车号牌应当按照规定悬挂并保持清晰、完整，不得故意遮挡、污损。</span></strong></p>', '正确#错误#', '1#', '0', '0', '《中华人民共和国道路交通安全法》第二章第十一条 驾驶机动车上道路行驶，应当悬挂机动车号牌，放置检验合格标志、保险标志，并随车携带机动车行驶证。 机动车号牌应当按照规定悬挂并保持清晰、完整，不得故意遮挡、污损。 任何单位和个人不得收缴、扣留机动车号牌。 因此该题目正确\n');
INSERT INTO `t_question` VALUES ('17', '2#5', '1', '<p><strong><span style=\"font-size: 10.5pt; font-family: 宋体;\">应当报废的机动车必须及时办理注销登记。</span></strong></p>', '正确#错误#', '1#', '0', '0', '《中华人民共和国道路交通安全法》第二章第一节 第十四条国家实行机动车强制报废制度，根据机动车的安全技术状况和不同用途，规定不同的报废标准。 应当报废的机动车必须及时办理注销登记。 达到报废标准的机动车不得上道路行驶。报废的大型客、货车及其他营运车辆应当在公安机关交通管理部门的监督下解体。因此该题正确\n');
INSERT INTO `t_question` VALUES ('18', '2#5', '1', '<p><strong><span style=\"font-size: 10.5pt; font-family: 宋体;\">任何单位或者个人不得伪造、变造、挪用机动车登记证书、号牌、行驶证、检验合格标志、保险标志。</span></strong></p>', '正确#错误#', '1#', '0', '0', '这是法律规定的。\n');
INSERT INTO `t_question` VALUES ('19', '2#5', '1', '<p><strong><span style=\"font-size: 10.5pt; font-family: 宋体;\">不得驾驶安全设施不全或者机件不符合技术标准等具有安全隐患的机动车。</span></strong></p>', '正确#错误#', '1#', '0', '0', '《中华人民共和国道路交通安全法》第二章第二节 第二十一条 驾驶人驾驶机动车上道路行驶前，应当对机动车的安全技术性能进行认真检查；不得驾驶安全设施不全或者机件不符合技术标准等具有安全隐患的机动车.因此该题正确\n');
INSERT INTO `t_question` VALUES ('20', '2#5', '1', '<p><strong><span style=\"font-size: 10.5pt; font-family: 宋体;\">驾驶机动车，应当遵守左侧通行的原则。</span></strong></p>', '正确#错误#', '2#', '0', '0', '《中华人民共和国道路交通安全法》第四章第一节 第三十五条 机动车、非机动车实行右侧通行.因此该题错误');
INSERT INTO `t_question` VALUES ('21', '2#5', '1', '<p><strong><span style=\"font-size: 10.5pt; font-family: 宋体;\">道路划分为机动车道、非机动车道和人行道的，机动车、非机动车、行人实行分道通行。</span></strong></p>', '正确#错误#', '1#', '0', '0', '《中华人民共和国道路交通安全法》第四章第一节 第三十六条 根据道路条件和通行需要，道路划分为机动车道、非机动车道和人行道的，机动车、非机动车、行人实行分道通行。没有划分机动车道、非机动车道和人行道的，机动车在道路中间通行，非机动车和行人在道路两侧通行。因此该题正确！！\n');
INSERT INTO `t_question` VALUES ('22', '2#5', '1', '<p><strong><span style=\"font-size: 10.5pt; font-family: 宋体;\">道路划设专用车道的，在专用车道内，其他车辆可以借道超车。</span></strong></p>', '正确#错误#', '2#', '0', '0', '《中华人民共和国道路交通安全法》第四章第一节 第三十七条 道路划设专用车道的，在专用车道内，只准许规定的车辆通行，其他车辆不得进入专用车道内行驶。所以本题是错的。');
INSERT INTO `t_question` VALUES ('23', '2#5', '1', '<p><strong><span style=\"font-size: 10.5pt; font-family: 宋体;\">小型机动车可以超越执行紧急任务的警车。</span></strong></p>', '正确#错误#', '2#', '0', '0', '《中华人民共和国道路交通管理条例》第九章 第七十六条 机动车驾驶员有下列行为之一的，处一百元以下罚款或者警告，可以并处吊扣四个月以下驾驶证：（一）驾驶与驾驶证准驾车型不相符合的车辆的；（二）不按规定参加驾驶员审验或者审验不合格仍驾驶车辆的；（三）用人工直接供油驾驶车辆的（四）驾车穿插、超越警车及其护卫车队的.所以此题错误');
INSERT INTO `t_question` VALUES ('24', '2#5', '1', '<p><strong><span style=\"font-size: 10.5pt; font-family: 宋体;\">机动车行经交叉路口，不得超车。</span></strong></p>', '正确#错误#', '1#', '0', '0', '中华人民共和国道路交通安全法》第四十三条 同车道行驶的机动车，后车应当与前车保持足以采取紧急制动措施的安全距离。有下列情形之一的，不得超车：行经铁路道口、交叉路口、窄桥、弯道、陡坡、隧道、人行横道、市区交通流量大的路段等没有超车条件的。 通过隧道，铁路道口，急转弯路段，窄路，窄桥或遇前方道路上有车辆掉头时，不得超车。所以此题是对的。');
INSERT INTO `t_question` VALUES ('28', '1#3', '1', '<p><span style=\"font-size: 14px;font-family: 宋体\">图中标志的含义是<span style=\"text-decoration:underline;\"> &nbsp;&nbsp;</span>。</span><img src=\"/drive/fileupload/image/20190709/1562656854057095615.png\" title=\"1562656854057095615.png\" alt=\"1562656854057095615.png\" width=\"100\" height=\"100\"/></p>', '向右行驶#绕行#向左急弯路#向右急弯路#', '3#', '0', '0', '显然。');
INSERT INTO `t_question` VALUES ('29', '1#3', '1', '<p><span style=\"font-size: 14px;font-family: 宋体\">图中所示警告标志的作用是<span style=\"text-decoration:underline;\">&nbsp;&nbsp; </span>。</span><img src=\"/drive/fileupload/image/20190709/1562657040836007603.png\" title=\"1562657040836007603.png\" alt=\"1562657040836007603.png\" width=\"100\" height=\"100\"/></p>', '警告车辆、行人注意前方交叉路口#指示车辆和行人行进#禁止或限制车辆和行人通过前方交叉路口#传递道路方向、地点、距离信息#', '1#', '0', '0', '该标志为一个三角形，内部图案为一个倒T形，因此意思是警告车辆和行人注意前方交叉路口。');
INSERT INTO `t_question` VALUES ('30', '1#3', '1', '<p><span style=\"font-size: 14px;font-family: 宋体\">图中所示禁令标志的作用是<span style=\"text-decoration:underline;\">&nbsp;&nbsp; </span>。</span><img src=\"/drive/fileupload/image/20190709/1562657160778028538.png\" title=\"1562657160778028538.png\" alt=\"1562657160778028538.png\" width=\"100\" height=\"100\"/></p>', '警告车辆和行人注意小型汽车#禁止小型机动车通行#指示机动车行进#禁止所有机动车通行#', '4#', '0', '0', '小汽车标志表示所有机动车。');
INSERT INTO `t_question` VALUES ('31', '1#3', '1', '<p><span style=\"font-size: 14px;font-family: 宋体\">图中指示标志的作用是指示车辆、行人<span style=\"text-decoration:underline;\">&nbsp;&nbsp; </span>。</span><img src=\"/drive/fileupload/image/20190709/1562657237401034564.png\" title=\"1562657237401034564.png\" alt=\"1562657237401034564.png\" width=\"100\" height=\"100\"/></p>', '注意危险地点#按标志指示的路线、方向行驶#注意行驶#可以通行的方向，但可以不按指示的方向通行#', '2#', '0', '0', '显然。');
INSERT INTO `t_question` VALUES ('32', '1#3', '1', '<p><span style=\"font-size: 14px;font-family: 宋体\">图中标志的含义是<span style=\"text-decoration:underline;\">&nbsp;&nbsp; </span>。</span><img src=\"/drive/fileupload/image/20190709/1562657327199054529.png\" title=\"1562657327199054529.png\" alt=\"1562657327199054529.png\" width=\"100\" height=\"100\"/></p>', '下陡坡#滑行#下行#上陡坡#', '1#', '0', '0', '图中标志表示下陡坡。');
INSERT INTO `t_question` VALUES ('33', '1#3', '1', '<p><span style=\"font-size: 14px;font-family: 宋体\">图中标志的含义是<span style=\"text-decoration:underline;\">&nbsp;&nbsp; </span>。</span><img src=\"/drive/fileupload/image/20190709/1562657431194011714.png\" title=\"1562657431194011714.png\" alt=\"1562657431194011714.png\" width=\"100\" height=\"100\"/></p>', '村庄#隧道#漫水桥#堤坝路#', '4#', '0', '0', '显然为堤坝路');
INSERT INTO `t_question` VALUES ('34', '1#3', '1', '<p><span style=\"font-size: 14px;font-family: 宋体\">&nbsp;图中标志的含义是<span style=\"text-decoration:underline;\">&nbsp;&nbsp; </span>。</span><img src=\"/drive/fileupload/image/20190709/1562657585648068039.png\" title=\"1562657585648068039.png\" alt=\"1562657585648068039.png\" width=\"100\" height=\"100\"/></p>', '渡口#堤坝路#驼峰桥#漫水桥#', '1#', '0', '0', '有水有船为渡口');
INSERT INTO `t_question` VALUES ('35', '1#3', '1', '<p><span style=\"font-size: 14px;font-family: 宋体\">图中标志的含义是<span style=\"text-decoration:underline;\">&nbsp;&nbsp; </span>。</span><img src=\"/drive/fileupload/image/20190709/1562657690477037017.png\" title=\"1562657690477037017.png\" alt=\"1562657690477037017.png\" width=\"100\" height=\"100\"/></p>', '学校#村庄#傍山险路#注意落石#', '2#', '0', '0', '显然');
INSERT INTO `t_question` VALUES ('36', '1#3', '1', '<p><span style=\"font-size: 14px;font-family: 宋体\">&nbsp;图中标志的含义是<span style=\"text-decoration:underline;\">&nbsp;&nbsp; </span>。</span><img src=\"/drive/fileupload/image/20190709/1562657810778032918.png\" title=\"1562657810778032918.png\" alt=\"1562657810778032918.png\" width=\"100\" height=\"100\"/></p>', '傍山险路#注意行人#注意儿童 #施工#', '4#', '0', '0', '显然有人施工');
INSERT INTO `t_question` VALUES ('37', '1#3', '1', '<p><span style=\"font-size: 14px;font-family: 宋体\">图中标志的含义是<span style=\"text-decoration:underline;\">&nbsp;&nbsp; </span>。</span><img src=\"/drive/fileupload/image/20190709/1562657907126098448.png\" title=\"1562657907126098448.png\" alt=\"1562657907126098448.png\" width=\"100\" height=\"100\"/></p>', '急弯路 #连续弯路#曲线行驶#禁止转弯#', '2#', '0', '0', '该题做不出来不建议考驾照呢，亲。');
INSERT INTO `t_question` VALUES ('38', '2#3', '1', '<p><span style=\"font-size: 10.5pt; font-family: 宋体;\">图中标志是分流诱导标志，表示前方有分流车道，车辆应按箭头方向直行或驶出主车道。</span><img src=\"/drive/fileupload/image/20190709/1562658208399078344.png\" title=\"1562658208399078344.png\" alt=\"1562658208399078344.png\" width=\"100\" height=\"100\"/></p>', '正确#错误#', '1#', '0', '0', '请发挥主观想象力');
INSERT INTO `t_question` VALUES ('39', '2#3', '1', '<p><span style=\"font-size: 10.5pt; font-family: 宋体;\">图中标志的含义是表示车辆向右行驶。</span><img src=\"/drive/fileupload/image/20190709/1562658661944059982.png\" title=\"1562658661944059982.png\" alt=\"1562658661944059982.png\" width=\"100\" height=\"100\"/></p>', '正确#错误#', '2#', '0', '0', '该题不会不建议考驾照呢，亲');
INSERT INTO `t_question` VALUES ('40', '1#3#4', '1', '<p style=\"margin-left:70px\"><span style=\"font-family:宋体;color:black\">如图所示限制速度标记，用于需要限制车辆最高行驶速度的车道起点和其它适&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 当位置，表示机动车<span style=\"text-decoration:underline;\">&nbsp;&nbsp; </span>。<img src=\"/drive/fileupload/image/20190709/1562658782649089013.png\" title=\"1562658782649089013.png\" alt=\"1562658782649089013.png\" width=\"100\" height=\"100\"/></span></p><p><br/></p>', '平均行驶速度标准#最低行驶速度不得低于标记所示规定#最高行驶速度不得超过标记所示规定#设计时速标准#', '3#', '0', '0', '不建议挑战和谐社会');
INSERT INTO `t_question` VALUES ('41', '2#3', '1', '<p><span style=\"font-size: 10.5pt; font-family: 宋体;\">图中所示斑马状导流线，表示车辆应按规定的路线行驶，可以压线或越线行驶。</span><img src=\"/drive/fileupload/image/20190709/1562658926197044662.png\" title=\"1562658926197044662.png\" alt=\"1562658926197044662.png\" width=\"100\" height=\"100\"/></p>', '正确#错误#', '2#', '0', '0', '不用看，图里面全是实线，实线是不允许碾压的！所以错了！');
INSERT INTO `t_question` VALUES ('42', '2#3', '1', '<p><span style=\"font-size: 10.5pt; font-family: 宋体;\">图中所示黄色虚线内的专用车道，用以指示仅限于某车种行驶，其他车种可借道超车或长距离行驶。</span><img src=\"/drive/fileupload/image/20190709/1562659074873058532.png\" title=\"1562659074873058532.png\" alt=\"1562659074873058532.png\" width=\"100\" height=\"100\"/></p>', '正确#错误#', '2#', '0', '0', '既然是专用车道，其他车辆当然不能借道超车或是长距离行驶。');
INSERT INTO `t_question` VALUES ('43', '2#3', '1', '<p><span style=\"font-size: 10.5pt; font-family: 宋体;\">图中所示地面标识是表示出租车专用上下客车位，其他车辆可临时停车。</span><img src=\"/drive/fileupload/image/20190709/1562659184366016916.png\" title=\"1562659184366016916.png\" alt=\"1562659184366016916.png\" width=\"100\" height=\"100\"/></p>', '正确#错误#', '2#', '0', '0', '那三个字叫出租车！');
INSERT INTO `t_question` VALUES ('44', '1#3', '1', '<p><span style=\"font-size: 14px;font-family: 宋体\">&nbsp;图中警察手势为<span style=\"text-decoration:underline;\">&nbsp;&nbsp; </span>信号。</span><img src=\"/drive/fileupload/image/20190709/1562659313916060956.png\" title=\"1562659313916060956.png\" alt=\"1562659313916060956.png\" width=\"100\" height=\"100\"/></p>', '示意车辆靠边停车#减速慢行#停止#右转弯#', '4#', '0', '0', '建议多上马路实践实践');
INSERT INTO `t_question` VALUES ('45', '2#3', '1', '<p><span style=\"font-size: 10.5pt; font-family: 宋体;\">&nbsp;如图所示中心圈，设在平面交叉路口的中心，用以区分车辆大、小转弯，及交叉路口车辆左右转弯的指示，车辆不得压线行驶。</span><img src=\"/drive/fileupload/image/20190709/1562659528295003912.png\" title=\"1562659528295003912.png\" alt=\"1562659528295003912.png\" width=\"100\" height=\"100\"/></p>', '正确#错误#', '1#', '0', '0', '一般警察都站到这个圈里，你敢压不！');
INSERT INTO `t_question` VALUES ('46', '2#3', '1', '<p><span style=\"font-size: 10.5pt; font-family: 宋体;\">如图所示白色标线框内的区域表示车辆停放位置。</span><img src=\"/drive/fileupload/image/20190709/1562659697746009602.png\" title=\"1562659697746009602.png\" alt=\"1562659697746009602.png\" width=\"100\" height=\"100\"/></p>', '正确#错误#', '1#', '0', '0', '框框里面用于房车');
INSERT INTO `t_question` VALUES ('47', '1#3', '1', '<p><span style=\"font-size: 14px;font-family: 宋体\">图中警察手势为<span style=\"text-decoration:underline;\">&nbsp;&nbsp; </span>信号。</span><img src=\"/drive/fileupload/image/20190709/1562659806501011426.png\" title=\"1562659806501011426.png\" alt=\"1562659806501011426.png\" width=\"100\" height=\"100\"/></p>', '示意靠边停车#示意抢劫#左转弯#右转弯#', '1#', '0', '0', '警察的举手是让你停车，不然请你喝茶？');
INSERT INTO `t_question` VALUES ('48', '2#5', '1', '<p><span style=\"font-size: 10.5pt; font-family: 宋体;\">一个合格的驾驶人，不仅表现在技术的娴熟上，更重要的是应该具有良好的驾驶行为习惯和道德修养。</span></p>', '正确#错误#', '1#', '0', '0', '此题道德修养就是说明要遵守交通规则');
INSERT INTO `t_question` VALUES ('49', '1#5', '1', '<p><span style=\"font-size: 14px;font-family: 宋体\">行车中需要借道绕过前方障碍物，但对向来车已接近障碍物时，应当<span style=\"text-decoration:underline;\">&nbsp;&nbsp; </span>。</span></p>', '降低速度或停车，让对向来车优先通行#加速提前抢过#鸣喇叭示意对向车辆让道#迅速占用车道，迫使对向来车停车让道#', '1#', '0', '0', '是相向的才是有阻碍的一方让无阻碍的一方啊，我们也应做到礼让啊，又不会吃亏。');
INSERT INTO `t_question` VALUES ('50', '1#5', '1', '<p><span style=\"font-size:14px;font-family:宋体\">行车中发现牲畜抢道时，应<span style=\"text-decoration:underline;\">&nbsp;&nbsp; </span>。</span></p>', '主动减速或停车避让#鸣喇叭驱赶#加速绕过#低速用车驱赶#', '1#', '0', '0', '显然');
INSERT INTO `t_question` VALUES ('51', '5#6', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">吴某驾驶一辆大客车，乘载33人（核载22人），行至163县道7公里加300米处时，机动车失控坠入山沟，造成10人死亡、21人受伤。事后经酒精检测，吴某血液酒精含量为26毫克/百毫升。吴某的主要违法行为是什么？</span></p>', '客车超员#酒后驾驶#超速行驶#疲劳驾驶#', '1#2#', '0', '0', '乘载33人(核载22人)，所以客车超员。\n吴某血液酒精含量为26毫克/百毫升，酒后驾驶。');
INSERT INTO `t_question` VALUES ('52', '5#6', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">钱某驾驶大型卧铺客车，乘载45人（核载40人），保持40公里/小时以上的车速行至八宿县境内连续下坡急转弯路段处，翻下100米深的山崖，造成17人死亡、20人受伤。钱某的主要违法行为是什么？</span></p>', '客车超员#驾驶时接听手持电话#疲劳驾驶#超速行驶#', '1#4#', '0', '0', '弯道限速30公里/每小时，保持40公里/小时以上的车速是超速行驶。\n乘载45人(核载40人)，客车超员。');
INSERT INTO `t_question` VALUES ('53', '5#6', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">邹某驾驶大型卧铺客车（核载35人，实载47人），行至京港澳高速公路938公里时，因乘车人携带的大量危险化学品在车厢内突然发生爆燃，造成41人死亡，6人受伤。此事故中的主要违法行为是什么？</span></p>', '乘车人携带易燃易爆危险物品#不按规定停车#超速行驶#客车超员#', '1#4#', '0', '0', '核载35人，实载47人客车超员。\n乘车人携带的大量危险化学品在车厢内突然发生爆燃，属于乘车人携带易燃易爆危险物品。');
INSERT INTO `t_question` VALUES ('54', '2#3', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">在这种能见度的情况下起步要开启近光灯。</span><img src=\"/drive/fileupload/image/20190709/1562661036776014533.jpg\" title=\"1562661036776014533.jpg\" alt=\"1562661036776014533.jpg\" width=\"100\" height=\"100\"/></p>', '正确#错误#', '1#', '0', '0', '冰雪等天气情况下起步要开启近光灯。一般雪天能见度低，应该注意灯光的正确使用。一是开启雾灯、近光灯，帮助驾驶员瞭望前方情况，使驾驶员对前方情况看得清楚一些。二是开启示廓灯和前后位灯，示意自己车辆的存在，使前后行驶的车辆，能够看到自己的具体位置及通行情况，方便他们采取相应的措施。');
INSERT INTO `t_question` VALUES ('55', '2#3', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">驾驶机动车向左变更车道遇到这种情况要注意让行。</span><img src=\"/drive/fileupload/image/20190709/1562661100537083586.jpg\" title=\"1562661100537083586.jpg\" alt=\"1562661100537083586.jpg\" width=\"100\" height=\"100\"/></p>', '正确#错误#', '1#', '0', '0', '因前面车辆已经亮刹车灯，可能出现一定情况，且左侧也有车辆在较近距离行驶，要尽量注意让行。');
INSERT INTO `t_question` VALUES ('56', '2#3', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">驾驶机动车遇到这种情况时要向左占道行驶。</span><img src=\"/drive/fileupload/image/20190709/1562661173066020534.jpg\" title=\"1562661173066020534.jpg\" alt=\"1562661173066020534.jpg\" width=\"100\" height=\"100\"/></p>', '正确#错误#', '2#', '0', '0', '如图，前方黑车逆行，为了安全，应该靠右减速或停车让行。');
INSERT INTO `t_question` VALUES ('57', '1#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">夜间驾驶机动车在照明条件良好的路段跟车行驶怎样使用灯光？</span></p>', '关闭所有车灯#使用近光灯#使用远光灯#关闭前照灯#', '2#', '0', '0', '夜间跟车时后车不允许使用远光，应提前变换为近光灯。');
INSERT INTO `t_question` VALUES ('58', '5#6', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">下列做法哪些可以有效避免驾驶疲劳？</span></p>', '餐后适当休息后驾车#用餐不宜过饱#保持良好的睡眠#连续驾驶不超过4小时#', '1#2#3#4#', '0', '0', '常识题。可以有效避免驾驶疲劳有【连续驾驶不超过4小时】【用餐不宜过饱】【保持良好的睡眠】【餐后适当休息后驾车】的做法。');
INSERT INTO `t_question` VALUES ('59', '1#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">赵某（持有A2驾驶证）驾驶大型卧铺客车，行驶至叶城县境内219国道226公里加215米处转弯路段时，坠入道路一侧山沟，致16人死亡，26人受伤。赵某的主要违法行为是什么？</span></p>', '驾驶与准驾车型不符的机动车#客车超员#疲劳驾驶#驾驶逾期未检验的机动车#', '1#', '0', '0', '持有A2驾驶证驾驶大型卧铺客车，驾驶与准驾车型不符的机动车。');
INSERT INTO `t_question` VALUES ('60', '1#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">会车前选择的交会位置不理想时，应怎样做？</span></p>', '打开前照灯，示意对方停车让行#减速、低速会车或停车让行#加速选择理想位置#向左占道，让对方减速让行#', '2#', '0', '0', '发现交会位置不理想时，应减速或停车让行，以寻找下一个理想会车位置。');
INSERT INTO `t_question` VALUES ('61', '1#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">进入左侧道路超车，无法保证与正常行驶前车的横向安全间距时，应怎样做？</span></p>', '放弃超车#并行一段时间后超车#加速超车#稍后超车#', '1#', '0', '0', '没有超车条件，放弃超车是最安全的行为');
INSERT INTO `t_question` VALUES ('62', '1#4', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">车辆在山区道路跟车行驶时，应怎样做？</span></p>', '紧随前车之后#尽可能寻找超车机会#适当加大安全距离#适当减少安全距离#', '3#', '0', '0', '安全驾驶，保持安全距离。');
INSERT INTO `t_question` VALUES ('63', '1#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">山区道路车辆进入弯道前，在对面没有来车的情况下，应怎样做？</span></p>', '应减速鸣喇叭靠右行#可靠弯道外侧行驶#可加速沿弯道切线方向通过#可短时间借用对方车道#', '1#', '0', '0', '题目是驶入弯道前，必须鸣笛，因为不确定是否有车辆，减速是必须的，避免有车相撞。通过弯道，减速、鸣喇叭、靠右行，是最安全的做法。');
INSERT INTO `t_question` VALUES ('64', '1#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">驾驶车辆通过无人看守的铁路道口时，应怎样做？</span></p>', '加速通过#减速通过#匀速通过#一停，二看，三通过#', '4#', '0', '0', '一停，是停在未到铁道前，不是停在铁路上。二看，是在铁道前观察是否有火车要经过。三通过，才是安全通过。');
INSERT INTO `t_question` VALUES ('65', '2#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">驾驶机动车下长坡时，仅靠行车制动器制动，容易引起行车制动器失灵。</span></p>', '正确#错误#', '1#', '0', '0', '汽车制动分为三种：\n1、行车制动，就是脚下的制动踏板，控制四轮；\n2、驻车制动，就是手刹车，停车时防止前滑后溜；\n3、发动机制动，也就是抢档，用于刹车失灵，在行车制动失灵时用，一级一级减档，从高到底，利用发动机变速箱的原理使车速降下来。\n下长坡时，驾驶员长时间使用行车制动器，易造成制动器热衰退，汽车的制动效能变差。');
INSERT INTO `t_question` VALUES ('66', '2#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">驾驶机动车下长坡时，空挡滑行会导致再次挂挡困难。</span></p>', '正确#错误#', '1#', '0', '0', '驾驶机动车下长坡时，空挡滑行会导致再次挂挡困难。');
INSERT INTO `t_question` VALUES ('67', '2#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">驾驶机动车超车时，前方车辆不减速让路，应停止超车并适当减速，与前方车辆保持安全距离。</span></p>', '正确#错误#', '1#', '0', '0', '不让超车，就别超了，安全第一。');
INSERT INTO `t_question` VALUES ('68', '2#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">伤员骨折处出血时，先固定好肢体再进行止血和包扎。</span></p>', '正确#错误#', '1#', '0', '0', '伤员骨折处出血时，应先止血和消毒，然后再固定。');
INSERT INTO `t_question` VALUES ('69', '1#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">当驾驶人驶出隧道时，出现下图所示的“明适应”现象时，以下做法正确的是什么？</span><img src=\"/drive/fileupload/image/20190709/1562662383104027793.jpg\" title=\"1562662383104027793.jpg\" alt=\"1562662383104027793.jpg\" width=\"100\" height=\"100\"/></p>', '加速使出隧道#减少与前车的距离，利用前车挡出强光#变更至车辆较少的车道，迅速使出隧道#与前车保持安全距离，切记盲目加速#', '4#', '0', '0', '驾驶机动车驶出隧道时切勿在眼睛“明适应”过程中盲目加速，保证安全驾驶。');
INSERT INTO `t_question` VALUES ('70', '3#6', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">驾驶机动车途经这个路段的时候，以下关于潜在风险的说法正确的是？</span><img src=\"/drive/fileupload/image/20190709/1562662623766005935.jpg\" title=\"1562662623766005935.jpg\" alt=\"1562662623766005935.jpg\" width=\"100\" height=\"100\"/></p>', '坡顶可能来一辆车#对面驶来的车辆可能占用你的车道#前方道路可能有障碍物#前方道路可能有弯路#', '2#4#', '0', '0', '驾驶机动车在接近坡顶时，需要考虑到视线受阻的情况，以及一切可能的潜在风险。');
INSERT INTO `t_question` VALUES ('71', '1#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">当你看到对面有车辆超车时，应该如何应对？</span></p>', '加速，并向左侧越线行驶#减速，并向右侧闪避#减速，并向左侧避让#保持原有驾驶方向和速度行驶#', '2#', '0', '0', '应对这种情况要当机立断。预判对方车辆是否能够有安全超车的可能，对方能够安全超车就主动提前减速，保持安全距离以供对方超车；对方不能够安全超车，就马上闪灯加鸣笛告知，保持常速行驶即可，对方知道后便会放弃超车。');
INSERT INTO `t_question` VALUES ('72', '2#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">驾驶机动车起火时，要设法将机动车停在远离城镇、建筑物、树木、机动车及易燃物的空旷地带，并及时把事故情况和地点通报给救援机构。</span></p>', '正确#错误#', '1#', '0', '0', '注意本题中出现的“设法”二字，也就是说尽可能把损失和伤害降到最低，因此应该如题中这么做，本题正确。');
INSERT INTO `t_question` VALUES ('73', '1#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">在事故现场抢救伤员的基本要求是什么？</span></p>', '先救命，后治伤#先帮助轻伤员#后救助重伤员#先治伤，后救命#', '1#', '0', '0', '优先救治有生命危险的，再救受伤的。受伤的人员没有生命危险的还可以暂缓一下，有生命危险的救治不及时就可能造成伤者死亡。');
INSERT INTO `t_question` VALUES ('74', '2#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">遇伤者被压于车轮或货物下时，要立即拉拽伤者的肢体将其拖出。</span></p>', '正确#错误#', '2#', '0', '0', '不能硬拽，车轮压住了伤者，必须将车轮或者货物移开后才能将伤者移出，如果硬拖，会使伤者受伤更加严重。');
INSERT INTO `t_question` VALUES ('75', '2#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">受伤者在车内无法自行下车时，可设法将其从车内移出，尽量避免二次受伤。</span></p>', '正确#错误#', '1#', '0', '0', '伤者无法自行下车，就说明伤者行动不便，这时应设法将其移出，以免汽车发生突发状况，造成第二次伤害。');
INSERT INTO `t_question` VALUES ('76', '1#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">抢救昏迷失去知觉的伤员需注意什么？</span></p>', '使劲掐伤员的人中#马上实施心肺复苏#抢救前先检查呼吸#连续拍打伤员面部#', '3#', '0', '0', '抢救昏迷的伤员时，应先确认伤员的生命体征，也就是先检查呼吸。然后再根据情况进行施救。');
INSERT INTO `t_question` VALUES ('77', '2#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">搬运昏迷失去知觉的伤员首先要采取仰卧位。</span></p>', '正确#错误#', '2#', '0', '0', '正确的做法是首先开放气道，再采取去枕仰卧位，头偏向一侧，保持呼吸道通畅，以防窒息。记住首先是放开气道，再采取仰卧位。');
INSERT INTO `t_question` VALUES ('78', '2#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">抢救昏迷失去知觉的伤员要在抢救前先检查呼吸。</span></p>', '正确#错误#', '1#', '0', '0', '检查呼吸的目的是为了了解伤员的生命体征，这是必须要先确认的。');
INSERT INTO `t_question` VALUES ('79', '1#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">抢救失血伤员时，要先采取什么措施？</span></p>', '观察#包扎#询问#止血#', '4#', '0', '0', '既然是失血伤员，首先要做的当然是止血。');
INSERT INTO `t_question` VALUES ('80', '1#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">在没有绷带急救伤员的情况下，以下救护行为中错误的是什么？</span></p>', '用手巾包扎#用细绳包扎#用手帕包扎#用棉质衣服包扎#', '2#', '0', '0', '首先看清题意，问的是错误的做法。明显细绳不能用来包扎伤口，因为细绳表面不是平整光滑的，也不够柔软，只会让伤口更加严重。');
INSERT INTO `t_question` VALUES ('81', '1#4', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">采用指压止血法为动脉出血伤员止血时，拇指压住伤口的什么位置？</span></p>', '近心端动脉#血管中部#血管下方动脉#远心端动脉#', '1#', '0', '0', '近心端就是靠近心脏方向的一端。动脉血管中血液的流动依靠心脏搏动来完成，如果动脉血管出血，压迫近心端血管就可以降低心脏对血液的传递，达到减少出血的目的。因此选择“近心端动脉”。');
INSERT INTO `t_question` VALUES ('82', '1#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">包扎止血不能用的物品是什么？</span></p>', '止血带#三角巾#麻绳#绷带#', '3#', '0', '0', '首先看清题意，问的是不能用的物品。明显粗糙的麻绳是不能用来止血包扎的，其表面不是平整光滑的，也不够柔软，用了只会加重伤势。\n包扎止血，要求包扎物表面平整而且松软，这样才能有效地扎紧受伤部位体内的血管，阻止血管内血液的再流通，达到止血的目的。');
INSERT INTO `t_question` VALUES ('83', '2#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">在没有绷带急救伤员的情况下，可用毛巾、手帕、床单、长筒尼龙袜子等代替绷带包扎。</span></p>', '正确#错误#', '1#', '0', '0', '上述的物品质地都较为柔软，在没有绷带的情况下可作为替代物使用，根据受伤位置的不同和创面的大小，你可以利用毛巾、手帕做成简易的三角巾，用于手臂骨折的固定等，长筒尼龙袜子可以作为固定的捆绑绳。');
INSERT INTO `t_question` VALUES ('84', '2#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">在紧急情况下为伤员止血时，须先用压迫法止血后再根据出血情况改用其他止血法。</span></p>', '正确#错误#', '1#', '0', '0', '一般小动脉和静脉出血可用加压包扎止血法，较大的动脉出血，应用止血带止血。但在紧急情况下，须先用压迫法止血，然后再根据出血情况改用其它止血法。指压止血法可以在较大的动脉出血后，用拇指压住出血的血管上方(近心端)，使血管被压闭住，中断血液。\n不需要大家理解其中原理，只需牢记即可。');
INSERT INTO `t_question` VALUES ('85', '2#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">救助失血过多出现休克的伤员要采取保暖措施。</span></p>', '正确#错误#', '1#', '0', '0', '失血过多+休克的伤员。注意是休克，休克的意思是血压下降，口渴，体温下降，意识模糊，皮肤发白，尿量减少的一种状态。所以要采取保暖措施.\n不需要大家理解其中原理，只需要记住即可。');
INSERT INTO `t_question` VALUES ('86', '1#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">救助全身燃烧伤员采取哪种应急措施？</span></p>', '用灭火器进行灭火#用沙土覆盖火焰灭火#向身上喷冷水灭火#帮助脱掉燃烧的衣服#', '4#', '0', '0', '救助全身燃烧伤员采取的最安全的方式是向身上喷冷水灭火。其他的方式或多或少会对伤员有害或者加重伤情。\n首先大家要明确，燃烧过后人体皮肤已经受损。而沙土上附着的病原体会感染受伤者的皮肤，事后的清理和后续治疗也会相当的麻烦；灭火器喷出的东西也可能会对受伤皮肤造成伤害；脱去受伤人员燃烧的衣服可能对其皮肤造成二次伤害。');
INSERT INTO `t_question` VALUES ('87', '2#5', '4', '<p><span style=\"color: rgb(51, 51, 51); font-family: &quot;Microsoft YaHei&quot;, &quot;Hiragino Sans GB&quot;, &quot;Hiragino Sans GB W3&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 18px;\">烧伤伤员口渴时，可喝少量的淡盐水。</span></p>', '正确#错误#', '1#', '0', '0', '这是由于皮肤大面积烧伤后有创面，会损失体液，按医学要求，烧伤后口渴时不能给伤员饮白开水。而淡盐水可补充体液。这是常识题。');
