@startuml
| 前端 |
start
: 管理员选择上传视频;
repeat
:管理员填写视频信息;
repeat while (视频信息格式不正确？)
: 将视频上传;
| 后端 |
: 服务器将视频下载到内部临时文件;
if (文件格式非mp4格式) then (yes)
    : 将视频转码为mp4格式;
endif
: 将视频移动至根目录文件夹下，\n并生成封面截图;
: 系统生成其视频与封面路径\n并与其他信息一起封装成bean;
: 调用方法，将该信息插入数据库;
| 前端 |
: 向前端返回操作结果信息;
end
@enduml