@startuml
    start
    :顺序练习界面;
    :答题界面;
    fork
    :评论试题;
    :在评论输入框中输入评论;
    :点击评论按钮;
    fork again
    :回复他人评论;
    :在他人评论右端点击回复按钮;
    :弹出新评论输入框;
    :输入评论，点击评论按钮;
    fork again
    :删除自己的某条评论;
    :在自己评论的右端点击删除按钮;
    if (确认删除？) then (是)
    :删除评论;
    else (否)
    :维持不变;
    endif
    end fork
    :上传评论数据;
    :更新答题界面;
    end
@enduml