@startuml
|前端|
start
:前端选择视频的ID;
:通过请求将参数发送到后台;
|后台|
:调用服务器方法，查询对应的视频;
if(视频存在) then (yes)
    :回执信息=视频存在;
else
    :回执信息=视频不存在;
endif
:将视频的播放路径和回执信息一起封装在map中;
:返回map的json数据;
|前端|
:前端读取并解析对应数据;
end
@enduml