@startuml
|前端|
start
: 管理员选择删除视频;
:前端提示确定删除;
if (确定删除) then (yes)
    |前端|
    :APP同时自动读取视频ID;
    :通过网页请求将数据传输到后台;
    |后台|
    :系统将参数封装入bean中;
    :调用服务的更新操作;
    |前端|
    :返回处理结果;
    end
else
    end
endif

@enduml